### PR TITLE
Replace mirror with apache archive to support old versions

### PR DESCRIPTION
**Pull request by ddseapy**

### CODE REVIEW

**Comment by djr7m** [comment]
I think @jahhulbert-ccri and I may have discussed something like this in a past P/R. I think the Archive server is the way to go if we really want people to be able to change the config to use "non current" versions of things. Any reason not to switch to using Archive server over mirror server?

**Comment by djr7m** [comment]
fixes #63  I think

**Comment by jahhulbert-ccri** [comment]
i think there was no reason not to use the archive server.

**Comment by ddseapy** [comment]
so you are wanting to do it for more than just kafka?

**Comment by ddseapy** [comment]
I guess i'll replace the mirror then with archive in general and push another pr

**Comment by jahhulbert-ccri** [comment]
for old versions of hadoop and spark, etc. you need the archive server too.

**Comment by djr7m** [comment]
I pulled and I'm trying this. It seems to be working. I should work on #62 a bit so we can make sure we don't always delete the contents of our NFS share.

**Comment by djr7m** [comment]
I vote merge (do I get a vote?)

**Comment by ddseapy** [comment]
@jahhulbert-ccri you ok with this getting merged?

**Pull request merged**
